services:
  app:
    container_name: ${APPLICATION_NAME}
    image: ${REPOSITORY}/${APPLICATION_NAME}:${SCOPE}
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    ports:
      - ${SSO_EXTERNAL_PORT}:${SSO_INTERNAL_PORT}
    networks:
      - cownetwork
networks:
  cownetwork:
    external: true
